"""inicial

Revision ID: 40fb5b6dc831
Revises: 
Create Date: 2026-03-17 10:55:59.488071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40fb5b6dc831'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id_rol', sa.SmallInteger(), autoincrement=True, nullable=False),
    sa.Column('clave_rol', sa.String(length=10), nullable=False),
    sa.Column('nombre_rol', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id_rol'),
    sa.UniqueConstraint('clave_rol')
    )
    op.create_table('usuarios',
    sa.Column('id_usuario', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid_usuario', sa.String(length=36), nullable=False),
    sa.Column('nombre_completo', sa.String(length=120), nullable=False),
    sa.Column('username', sa.String(length=60), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('id_rol', sa.SmallInteger(), nullable=False),
    sa.Column('estatus', sa.Enum('activo', 'inactivo', 'bloqueado'), nullable=False),
    sa.Column('intentos_fallidos', sa.SmallInteger(), nullable=False),
    sa.Column('bloqueado_hasta', sa.DateTime(), nullable=True),
    sa.Column('ultimo_login', sa.DateTime(), nullable=True),
    sa.Column('token_2fa', sa.String(length=10), nullable=True),
    sa.Column('token_2fa_expira', sa.DateTime(), nullable=True),
    sa.Column('cambio_pwd_req', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id_usuario'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_rol'], ['roles.id_rol'], ),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('username'),
    sa.UniqueConstraint('uuid_usuario')
    )
    op.create_table('ajustes_inventario',
    sa.Column('id_ajuste', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipo_inventario', sa.Enum('materia_prima', 'producto_terminado'), nullable=False),
    sa.Column('id_referencia', sa.Integer(), nullable=False),
    sa.Column('cantidad_anterior', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('cantidad_nueva', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=False),
    sa.Column('autorizado_por', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['autorizado_por'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_ajuste')
    )
    op.create_table('cortes_diarios',
    sa.Column('id_corte', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fecha_corte', sa.Date(), nullable=False),
    sa.Column('total_ventas', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_tickets', sa.Integer(), nullable=False),
    sa.Column('total_piezas', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('efectivo', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tarjeta', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('transferencia', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cancelaciones', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('abierto', 'cerrado'), nullable=False),
    sa.Column('cerrado_por', sa.Integer(), nullable=True),
    sa.Column('cerrado_en', sa.DateTime(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cerrado_por'], ['usuarios.id_usuario'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_corte'),
    sa.UniqueConstraint('fecha_corte')
    )
    op.create_table('logs_sistema',
    sa.Column('id_log', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tipo', sa.Enum('error', 'acceso', 'cambio_usuario', 'venta', 'compra', 'produccion', 'ajuste_inv', 'solicitud', 'salida_efectivo', 'seguridad'), nullable=False),
    sa.Column('nivel', sa.Enum('INFO', 'WARNING', 'ERROR', 'CRITICAL'), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('modulo', sa.String(length=60), nullable=True),
    sa.Column('accion', sa.String(length=120), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('ip_origen', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('referencia_id', sa.Integer(), nullable=True),
    sa.Column('referencia_tipo', sa.String(length=60), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_log')
    )
    op.create_table('materias_primas',
    sa.Column('id_materia', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid_materia', sa.String(length=36), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('categoria', sa.String(length=60), nullable=True),
    sa.Column('unidad_base', sa.String(length=20), nullable=False),
    sa.Column('stock_actual', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('stock_minimo', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('merma_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('estatus', sa.Enum('activo', 'inactivo'), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id_usuario'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_materia'),
    sa.UniqueConstraint('uuid_materia')
    )
    op.create_table('proveedores',
    sa.Column('id_proveedor', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid_proveedor', sa.String(length=36), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('rfc', sa.String(length=13), nullable=True),
    sa.Column('contacto', sa.String(length=120), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.Column('estatus', sa.Enum('activo', 'inactivo'), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id_usuario'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_proveedor'),
    sa.UniqueConstraint('rfc'),
    sa.UniqueConstraint('uuid_proveedor')
    )
    op.create_table('recetas',
    sa.Column('id_receta', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid_receta', sa.String(length=36), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('rendimiento', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unidad_rendimiento', sa.String(length=20), nullable=False),
    sa.Column('precio_venta', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('estatus', sa.Enum('activo', 'inactivo'), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id_usuario'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_receta'),
    sa.UniqueConstraint('uuid_receta')
    )
    op.create_table('sesiones',
    sa.Column('id_sesion', sa.String(length=64), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('ip_inicio', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('csrf_token', sa.String(length=64), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('expira_en', sa.DateTime(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('ultimo_acceso', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_sesion')
    )
    op.create_table('compras',
    sa.Column('id_compra', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('folio', sa.String(length=20), nullable=False),
    sa.Column('id_proveedor', sa.Integer(), nullable=False),
    sa.Column('fecha_compra', sa.Date(), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id_usuario'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_proveedor'], ['proveedores.id_proveedor'], ),
    sa.PrimaryKeyConstraint('id_compra'),
    sa.UniqueConstraint('folio')
    )
    op.create_table('detalle_recetas',
    sa.Column('id_detalle_receta', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_receta', sa.Integer(), nullable=False),
    sa.Column('id_materia', sa.Integer(), nullable=False),
    sa.Column('cantidad_requerida', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('orden', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['id_materia'], ['materias_primas.id_materia'], ),
    sa.ForeignKeyConstraint(['id_receta'], ['recetas.id_receta'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_detalle_receta'),
    sa.UniqueConstraint('id_receta', 'id_materia', name='uq_det_receta_materia')
    )
    op.create_table('productos_terminados',
    sa.Column('id_producto', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid_producto', sa.String(length=36), nullable=False),
    sa.Column('id_receta', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('precio_venta', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('stock_actual', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('stock_minimo', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('estatus', sa.Enum('activo', 'inactivo'), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_receta'], ['recetas.id_receta'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_producto'),
    sa.UniqueConstraint('uuid_producto')
    )
    op.create_table('salidas_efectivo',
    sa.Column('id_salida', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('folio_salida', sa.String(length=20), nullable=False),
    sa.Column('id_proveedor', sa.Integer(), nullable=True),
    sa.Column('categoria', sa.Enum('compra_insumos', 'servicios_utilities', 'mantenimiento', 'otros'), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('monto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('fecha_salida', sa.Date(), nullable=False),
    sa.Column('estado', sa.Enum('pendiente', 'aprobada', 'rechazada'), nullable=False),
    sa.Column('id_corte', sa.Integer(), nullable=True),
    sa.Column('registrado_por', sa.Integer(), nullable=False),
    sa.Column('aprobado_por', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['aprobado_por'], ['usuarios.id_usuario'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_corte'], ['cortes_diarios.id_corte'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_proveedor'], ['proveedores.id_proveedor'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['registrado_por'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_salida'),
    sa.UniqueConstraint('folio_salida')
    )
    op.create_table('ventas',
    sa.Column('id_venta', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('folio_venta', sa.String(length=20), nullable=False),
    sa.Column('fecha_venta', sa.DateTime(), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('metodo_pago', sa.Enum('efectivo', 'tarjeta', 'transferencia', 'otro'), nullable=False),
    sa.Column('cambio', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('requiere_ticket', sa.Boolean(), nullable=False),
    sa.Column('estado', sa.Enum('abierta', 'completada', 'cancelada'), nullable=False),
    sa.Column('vendedor_id', sa.Integer(), nullable=False),
    sa.Column('id_corte', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_corte'], ['cortes_diarios.id_corte'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vendedor_id'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_venta'),
    sa.UniqueConstraint('folio_venta')
    )
    op.create_table('detalle_compras',
    sa.Column('id_detalle_compra', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_compra', sa.Integer(), nullable=False),
    sa.Column('id_materia', sa.Integer(), nullable=False),
    sa.Column('cantidad_comprada', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('unidad_compra', sa.String(length=20), nullable=False),
    sa.Column('factor_conversion', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('cantidad_base', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('costo_unitario', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['id_compra'], ['compras.id_compra'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_materia'], ['materias_primas.id_materia'], ),
    sa.PrimaryKeyConstraint('id_detalle_compra')
    )
    op.create_table('detalle_ventas',
    sa.Column('id_detalle_venta', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_venta', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('descuento_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['id_producto'], ['productos_terminados.id_producto'], ),
    sa.ForeignKeyConstraint(['id_venta'], ['ventas.id_venta'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_detalle_venta')
    )
    op.create_table('produccion',
    sa.Column('id_produccion', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('folio_lote', sa.String(length=20), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('id_receta', sa.Integer(), nullable=False),
    sa.Column('cantidad_lotes', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('piezas_esperadas', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('piezas_producidas', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('estado', sa.Enum('pendiente', 'en_proceso', 'finalizado', 'cancelado'), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=True),
    sa.Column('fecha_fin_estimado', sa.DateTime(), nullable=True),
    sa.Column('fecha_fin_real', sa.DateTime(), nullable=True),
    sa.Column('operario_id', sa.Integer(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id_usuario'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_producto'], ['productos_terminados.id_producto'], ),
    sa.ForeignKeyConstraint(['id_receta'], ['recetas.id_receta'], ),
    sa.ForeignKeyConstraint(['operario_id'], ['usuarios.id_usuario'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_produccion'),
    sa.UniqueConstraint('folio_lote')
    )
    op.create_table('tickets',
    sa.Column('id_ticket', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_venta', sa.Integer(), nullable=False),
    sa.Column('contenido_json', sa.JSON(), nullable=False),
    sa.Column('impreso', sa.Boolean(), nullable=False),
    sa.Column('generado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_venta'], ['ventas.id_venta'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_ticket'),
    sa.UniqueConstraint('id_venta')
    )
    op.create_table('detalle_produccion',
    sa.Column('id_det_prod', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_produccion', sa.Integer(), nullable=False),
    sa.Column('id_materia', sa.Integer(), nullable=False),
    sa.Column('cantidad_requerida', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('cantidad_merma', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('cantidad_descontada', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['id_materia'], ['materias_primas.id_materia'], ),
    sa.ForeignKeyConstraint(['id_produccion'], ['produccion.id_produccion'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_det_prod')
    )
    op.create_table('solicitudes_produccion',
    sa.Column('id_solicitud', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('folio_solicitud', sa.String(length=20), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('cantidad_solicitada', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('prioridad', sa.Enum('baja', 'media', 'alta'), nullable=False),
    sa.Column('estado', sa.Enum('pendiente', 'aprobada', 'en_produccion', 'atendida', 'cancelada'), nullable=False),
    sa.Column('nota', sa.Text(), nullable=True),
    sa.Column('solicitado_por', sa.Integer(), nullable=False),
    sa.Column('atendido_por', sa.Integer(), nullable=True),
    sa.Column('id_produccion', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['atendido_por'], ['usuarios.id_usuario'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_produccion'], ['produccion.id_produccion'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_producto'], ['productos_terminados.id_producto'], ),
    sa.ForeignKeyConstraint(['solicitado_por'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_solicitud'),
    sa.UniqueConstraint('folio_solicitud')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('solicitudes_produccion')
    op.drop_table('detalle_produccion')
    op.drop_table('tickets')
    op.drop_table('produccion')
    op.drop_table('detalle_ventas')
    op.drop_table('detalle_compras')
    op.drop_table('ventas')
    op.drop_table('salidas_efectivo')
    op.drop_table('productos_terminados')
    op.drop_table('detalle_recetas')
    op.drop_table('compras')
    op.drop_table('sesiones')
    op.drop_table('recetas')
    op.drop_table('proveedores')
    op.drop_table('materias_primas')
    op.drop_table('logs_sistema')
    op.drop_table('cortes_diarios')
    op.drop_table('ajustes_inventario')
    op.drop_table('usuarios')
    op.drop_table('roles')
    # ### end Alembic commands ###
