"""Cambios_v2

Revision ID: 9c390faeb787
Revises: 40fb5b6dc831
Create Date: 2026-03-17 11:03:17.177082

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9c390faeb787'
down_revision = '40fb5b6dc831'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unidades_presentacion',
    sa.Column('id_unidad', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_materia', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('simbolo', sa.String(length=20), nullable=False),
    sa.Column('factor_a_base', sa.Numeric(precision=14, scale=6), nullable=False),
    sa.Column('uso', sa.Enum('compra', 'receta', 'ambos'), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_materia'], ['materias_primas.id_materia'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_unidad'),
    sa.UniqueConstraint('id_materia', 'simbolo', name='uq_unidad_materia_simbolo')
    )
    op.create_table('mermas',
    sa.Column('id_merma', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipo_objeto', sa.Enum('materia_prima', 'producto_terminado', 'lote_produccion'), nullable=False),
    sa.Column('id_referencia', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('unidad', sa.String(length=20), nullable=False),
    sa.Column('causa', sa.Enum('caducidad', 'quemado_horneado', 'caida_accidente', 'error_produccion', 'rotura_empaque', 'contaminacion', 'otro'), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('id_produccion', sa.Integer(), nullable=True),
    sa.Column('registrado_por', sa.Integer(), nullable=False),
    sa.Column('fecha_merma', sa.DateTime(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_produccion'], ['produccion.id_produccion'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['registrado_por'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_merma')
    )
    with op.batch_alter_table('solicitudes_produccion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('folio_solicitud'))

    op.drop_table('solicitudes_produccion')
    with op.batch_alter_table('compras', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('compras_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuarios', ['creado_por'], ['id_usuario'])

    with op.batch_alter_table('detalle_compras', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_unidad_presentacion', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'unidades_presentacion', ['id_unidad_presentacion'], ['id_unidad'], ondelete='SET NULL')
        batch_op.drop_column('subtotal')

    with op.batch_alter_table('detalle_produccion', schema=None) as batch_op:
        batch_op.drop_column('cantidad_merma')

    with op.batch_alter_table('detalle_recetas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_unidad_presentacion', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cantidad_presentacion', sa.Numeric(precision=12, scale=4), nullable=True))
        batch_op.create_foreign_key(None, 'unidades_presentacion', ['id_unidad_presentacion'], ['id_unidad'], ondelete='SET NULL')

    with op.batch_alter_table('materias_primas', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('materias_primas_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuarios', ['creado_por'], ['id_usuario'])
        batch_op.drop_column('merma_pct')

    with op.batch_alter_table('proveedores', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('proveedores_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuarios', ['creado_por'], ['id_usuario'])

    with op.batch_alter_table('recetas', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('recetas_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuarios', ['creado_por'], ['id_usuario'])

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('usuarios_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuarios', ['creado_por'], ['id_usuario'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('usuarios_ibfk_1'), 'usuarios', ['creado_por'], ['id_usuario'], ondelete='SET NULL')

    with op.batch_alter_table('recetas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('recetas_ibfk_1'), 'usuarios', ['creado_por'], ['id_usuario'], ondelete='SET NULL')

    with op.batch_alter_table('proveedores', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('proveedores_ibfk_1'), 'usuarios', ['creado_por'], ['id_usuario'], ondelete='SET NULL')

    with op.batch_alter_table('materias_primas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('merma_pct', mysql.DECIMAL(precision=5, scale=2), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('materias_primas_ibfk_1'), 'usuarios', ['creado_por'], ['id_usuario'], ondelete='SET NULL')

    with op.batch_alter_table('detalle_recetas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('cantidad_presentacion')
        batch_op.drop_column('id_unidad_presentacion')

    with op.batch_alter_table('detalle_produccion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cantidad_merma', mysql.DECIMAL(precision=12, scale=4), nullable=False))

    with op.batch_alter_table('detalle_compras', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subtotal', mysql.DECIMAL(precision=12, scale=2), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_unidad_presentacion')

    with op.batch_alter_table('compras', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('compras_ibfk_1'), 'usuarios', ['creado_por'], ['id_usuario'], ondelete='SET NULL')

    op.create_table('solicitudes_produccion',
    sa.Column('id_solicitud', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('folio_solicitud', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('id_producto', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cantidad_solicitada', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('prioridad', mysql.ENUM('baja', 'media', 'alta'), nullable=False),
    sa.Column('estado', mysql.ENUM('pendiente', 'aprobada', 'en_produccion', 'atendida', 'cancelada'), nullable=False),
    sa.Column('nota', mysql.TEXT(), nullable=True),
    sa.Column('solicitado_por', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('atendido_por', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_produccion', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('creado_en', mysql.DATETIME(), nullable=False),
    sa.Column('actualizado_en', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['atendido_por'], ['usuarios.id_usuario'], name=op.f('solicitudes_produccion_ibfk_1'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_produccion'], ['produccion.id_produccion'], name=op.f('solicitudes_produccion_ibfk_2'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_producto'], ['productos_terminados.id_producto'], name=op.f('solicitudes_produccion_ibfk_3')),
    sa.ForeignKeyConstraint(['solicitado_por'], ['usuarios.id_usuario'], name=op.f('solicitudes_produccion_ibfk_4')),
    sa.PrimaryKeyConstraint('id_solicitud'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('solicitudes_produccion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('folio_solicitud'), ['folio_solicitud'], unique=True)

    op.drop_table('mermas')
    op.drop_table('unidades_presentacion')
    # ### end Alembic commands ###
